### ISSUE TITLE
[Feature] BentoML API 부분에서 memory checking 기능 추가

### ISSUE THREAD

**Issue by jsujeon** [kms7530/Salsa#11]
## 내용
- 서비스 실행 전에 필요한 메모리를 미리 확인하고, 사용 가능한 메모리가 충분하지 않을 경우 적절한 에러를 발생시켜 OOM 문제를 사전에 방지할 필요가 있음. 
- 각 서비스 클래스와 Bako 클래스에 메모리 체크 기능이 필요.

## 🏗️ Blue Print
- 현재 사용 가능한 메모리 확인 함수 작성
- 각 서비스별 메모리 측정 함수 작성
- 서비스 클래스의 메모리 사용량 config 파일에다 작성
- Bako 클래스에 총 메모리 사용량 체크 로직 추가
- 에러 처리 및 로깅 구현
- 테스트 코드 작성

- [x] kms7530/Salsa/issues/12
- [x] kms7530/Salsa/issues/14
- [x] kms7530/Salsa/issues/15
- [x] kms7530/Salsa/issues/17
- [x] kms7530/Salsa/issues/28

**Comment by kms7530** [comment]
PR #30 #32 의 merge로 인한 issue close.
